menubar: false
toolbar:
  - bold italic | undo redo | alignleft aligncenter alignright | bullist numlist outdent indent | table | link unlink | image

plugins:
  - table
  - link
  - image
  - paste
paste_retain_style_properties: "font-size"

